### ISSUE TITLE
Suggestion: Output Pump

### ISSUE THREAD

**Issue by inkdear** [dogboy21/simple-wooden-pipes#1]
Just a pump that places water in the world instead of taking it into a pipe. +9,9999999999999 pipe-dream (ha ha) points if such a pump were capable of placing water in the nearest empty spot within a radius (allowing it to fill small dug out areas with water, rather than requiring the output to be moved.) The utility would be in packs where you can't move water sources with buckets, which is something there are currently no proper low-tech solutions for. (except Flopper, but the lines of floppers you need to use to move water with them aren't really.... ahem.... visually immersive, compared to pipes.)

**Comment by dogboy21** [comment]
Hey,

sorry for answering this late, I totally forgot about your issue.

Simple Wooden Pipes is supposed to be a simple (like the name already suggests) and low-tech fluid transfer mod. I don't think that this idea fits my vision of the mod currently.
Maybe I will come back to this idea in the future.
