### ISSUE TITLE
(Suggestion) Add a config option to change which item enables the extraction mode

### ISSUE THREAD

**Issue by jawsawn** [dogboy21/simple-wooden-pipes#3]
I'm planning to use this mod in a "all wooden" themed pack and would like to use something else other than a piston to enable the pipe extraction mode. 
Aka add a config option for Blocks.PISTON.

**Comment by dogboy21** [comment]
I'll work on this when I'm back home from my vacation  (aka next week)

**Comment by dogboy21** [comment]
Added in Version 1.2
