### ISSUE TITLE
(Features) Pipe variants shouldn't connect; Way to handle hot liquids

### ISSUE THREAD

**Issue by aleferna12** [dogboy21/simple-wooden-pipes#4]
First of all, great mod!

Feature suggestions:

Stone pipes (or something similar) could be usefull for lava and other modded hot liquids.
There could be a variant for normal stone, granite, andesite and so on.

Variant pipes should not connect. Example: Oak wooden pipe not connecting to spruce wooden pipe. This would allow for simpler cable networks and would also be intuitive.

My regards.

**Comment by dogboy21** [comment]
Added in Version 1.2
